#!/bin/bash
# atd-code Module Publishing

USER_SITE=`python3 -m site --user-site`

MODULE_LIST=($ls*)  # List all files in the current directory

echo Updating Modules in $USER_SITE

for module in $MODULE_LIST ; do
	echo Updating: $module
	rsync -u -r --delete $module/ $USER_SITE/$module/
done

echo Modules updated.

exit
